import { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { rentLedger, rentReceipt } from '../services/bookingService.js';
import { useToast } from '../context/ToastContext.jsx';
import Button from '../components/Button.jsx';
import Loader from '../components/Loader.jsx';
import Modal from '../components/Modal.jsx';

const statusStyle = {
  PAID: 'bg-success/10 text-success',
  DUE: 'bg-warning/10 text-warning',
  OVERDUE: 'bg-danger/10 text-danger',
};

// Renders a receipt into a new window and triggers the print dialog.
function printReceipt(r) {
  const w = window.open('', '_blank', 'width=520,height=680');
  if (!w) return;
  w.document.write(`
    <html><head><title>Receipt ${r.receiptNo}</title>
    <style>
      body{font-family:ui-sans-serif,system-ui,sans-serif;color:#151C27;padding:40px;max-width:480px;margin:auto}
      h1{font-size:22px;margin:0}
      .eyebrow{font-family:ui-monospace,monospace;font-size:11px;letter-spacing:.2em;text-transform:uppercase;color:#4F46E5;margin-bottom:6px}
      .row{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #eee;font-size:14px}
      .row span:first-child{color:#6b7280}
      .total{font-size:28px;font-weight:800;color:#16a34a;margin-top:8px}
      .paid{display:inline-block;margin-top:20px;padding:4px 12px;border:2px solid #16a34a;color:#16a34a;border-radius:99px;font-weight:700;transform:rotate(-4deg)}
      footer{margin-top:32px;font-size:12px;color:#9ca3af}
    </style></head><body>
    <div class="eyebrow">NestSecure PG · Rent receipt</div>
    <h1>${r.pg.name}</h1>
    <p style="color:#6b7280;font-size:13px">${r.pg.address || ''}${
    r.pg.city ? ', ' + r.pg.city : ''
  }</p>
    <div class="row"><span>Receipt no</span><span>${r.receiptNo}</span></div>
    <div class="row"><span>Rent month</span><span>${r.periodLabel}</span></div>
    <div class="row"><span>Tenant</span><span>${r.tenant.name}</span></div>
    <div class="row"><span>Paid on</span><span>${new Date(
      r.paidOn
    ).toLocaleDateString('en-IN')}</span></div>
    <div class="row"><span>Amount paid</span><span class="total">₹${r.amount.toLocaleString(
      'en-IN'
    )}</span></div>
    <div class="paid">PAID</div>
    <footer>Generated by NestSecure PG. This is a system-generated receipt.</footer>
    </body></html>`);
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 300);
}

export default function RentLedger() {
  const { bookingId } = useParams();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [receipt, setReceipt] = useState(null);
  const toast = useToast();

  useEffect(() => {
    (async () => {
      try {
        const res = await rentLedger(bookingId);
        setData(res.data);
      } catch (err) {
        toast.error(err.message);
      } finally {
        setLoading(false);
      }
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [bookingId]);

  const openReceipt = async (invoiceId) => {
    try {
      const res = await rentReceipt(invoiceId);
      setReceipt(res.data);
    } catch (err) {
      toast.error(err.message);
    }
  };

  if (loading) return <Loader className="min-h-screen" />;
  if (!data)
    return (
      <div className="min-h-screen flex items-center justify-center text-ink/60">
        Ledger not found.
      </div>
    );

  const { booking, invoices, summary } = data;

  return (
    <div className="min-h-screen bg-paper py-12">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <Link
          to="/bookings"
          className="text-sm text-ink/60 hover:text-indigo-brand mb-4 inline-block"
        >
          ← Back to bookings
        </Link>

        <div className="mb-8">
          <p className="font-mono text-xs uppercase tracking-[0.2em] text-indigo-brand mb-2">
            Rent ledger
          </p>
          <h1 className="font-display font-extrabold text-4xl text-ink">
            {booking.pgName}
          </h1>
          <p className="text-ink/60 mt-1">{booking.city}</p>
        </div>

        {/* Summary */}
        <div className="grid grid-cols-3 gap-4 mb-8">
          <div className="bg-white rounded-xl2 shadow-card p-4">
            <p className="text-xs text-ink/50 mb-1">Months</p>
            <p className="font-mono font-bold text-2xl text-ink">
              {summary.paidMonths}/{summary.months}
            </p>
          </div>
          <div className="bg-white rounded-xl2 shadow-card p-4">
            <p className="text-xs text-ink/50 mb-1">Total paid</p>
            <p className="font-mono font-bold text-2xl text-success">
              ₹{summary.totalPaid.toLocaleString('en-IN')}
            </p>
          </div>
          <div className="bg-white rounded-xl2 shadow-card p-4">
            <p className="text-xs text-ink/50 mb-1">Outstanding</p>
            <p
              className={`font-mono font-bold text-2xl ${
                summary.totalDue > 0 ? 'text-danger' : 'text-ink/40'
              }`}
            >
              ₹{summary.totalDue.toLocaleString('en-IN')}
            </p>
          </div>
        </div>

        {/* Ledger */}
        <div className="bg-white rounded-xl2 shadow-card overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-ink/10 text-left text-ink/50">
                  <th className="px-5 py-3 font-semibold">Month</th>
                  <th className="px-5 py-3 font-semibold">Due</th>
                  <th className="px-5 py-3 font-semibold">Amount</th>
                  <th className="px-5 py-3 font-semibold">Status</th>
                  <th className="px-5 py-3 font-semibold text-right">Receipt</th>
                </tr>
              </thead>
              <tbody>
                {invoices.map((inv) => (
                  <tr key={inv._id} className="border-b border-ink/5 last:border-0">
                    <td className="px-5 py-3 font-semibold text-ink">
                      {inv.periodLabel}
                    </td>
                    <td className="px-5 py-3 text-ink/60">
                      {new Date(inv.dueDate).toLocaleDateString('en-IN')}
                    </td>
                    <td className="px-5 py-3 font-mono text-ink">
                      ₹{inv.amount.toLocaleString('en-IN')}
                    </td>
                    <td className="px-5 py-3">
                      <span
                        className={`px-2.5 py-1 rounded-full text-xs font-semibold ${
                          statusStyle[inv.status]
                        }`}
                      >
                        {inv.status}
                      </span>
                    </td>
                    <td className="px-5 py-3 text-right">
                      {inv.status === 'PAID' ? (
                        <button
                          onClick={() => openReceipt(inv._id)}
                          className="text-indigo-brand font-semibold hover:underline"
                        >
                          View
                        </button>
                      ) : (
                        <span className="text-ink/30">—</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* Receipt modal */}
      <Modal
        open={!!receipt}
        onClose={() => setReceipt(null)}
        title="Rent receipt"
        footer={
          <>
            <Button variant="ghost" size="sm" onClick={() => setReceipt(null)}>
              Close
            </Button>
            <Button size="sm" onClick={() => printReceipt(receipt)}>
              Print / Save PDF
            </Button>
          </>
        }
      >
        {receipt && (
          <div className="space-y-3">
            <div className="flex justify-between items-center">
              <span className="font-mono text-xs uppercase tracking-wide text-ink/40">
                {receipt.receiptNo}
              </span>
              <span className="px-2.5 py-1 rounded-full text-xs font-semibold bg-success/10 text-success">
                PAID
              </span>
            </div>
            <div className="rounded-xl bg-paper border border-ink/10 p-4 space-y-2 text-sm">
              <Row label="PG" value={receipt.pg.name} />
              <Row label="Rent month" value={receipt.periodLabel} />
              <Row label="Tenant" value={receipt.tenant.name} />
              <Row
                label="Paid on"
                value={new Date(receipt.paidOn).toLocaleDateString('en-IN')}
              />
              <div className="flex justify-between items-baseline pt-2 border-t border-ink/10">
                <span className="text-ink font-semibold">Amount</span>
                <span className="font-mono font-bold text-2xl text-success">
                  ₹{receipt.amount.toLocaleString('en-IN')}
                </span>
              </div>
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
}

function Row({ label, value }) {
  return (
    <div className="flex justify-between">
      <span className="text-ink/60">{label}</span>
      <span className="font-semibold text-ink">{value}</span>
    </div>
  );
}
